

export const APP_FEATURES =[
{
    id:"01",
    title: "Tailored Just for You",
    description:
    "Get interview questions and model answers based on role, experience and specific focus areas."
},
{
   id:"02",
   title: "Learn at Your Own Pace",
   description:
    "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed answers."
},
{
   id:"03",
   title: "Capture Your Insights",
   description:
    "Add personal notes to any question and pin impotant ones to the top - making your learning more organized."
},
{
   id:"04",
   title: "Understand the 'Why' Behind Answers",
   description:
   "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each Interview question."
},
{
   id:"05",
   title: "Save, Organize, and Revisit",
   description:
   "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation and turn your hard work into success. "
}

]